import { Link, ProjectInfo } from "./types";

export const links: Link[] = [
  { nameEng: "Home", hash: "#home" },
  { nameEng: "Offers", hash: "#offers" },
  { nameEng: "Case Studies", hash: "#projects" },
  { nameEng: "About", hash: "#about" },
  { nameEng: "Contact", hash: "#contact" },
];

export const projectsData: ProjectInfo[] = [
  {
    slug: "truckwise",
    title: "TruckWise",
    subtitle: "Digitizing commercial vehicle rental, investor workflows, and daily fleet operations in one product system",
    homepageSummary: "Digitizing logistics operations, investor workflows, and commercial vehicle rental into one product system.",
    description: "Logistics and commercial vehicle rental platform with centralized multi-role operations.",
    context: "TruckWise operates in logistics and transport, with a strong emphasis on performance, data, and operational visibility. Its public-facing brand also highlights tech-enabled execution and disciplined logistics delivery.",
    role: "Execution + Strategy Ownership",
    overview: "TruckWise needed more than a booking interface. The business had operational complexity across commercial vehicle rental, multi-role mobile workflows, investor/shareholder coordination, contracts, expenses, maintenance, and document verification. The real challenge was turning disconnected, paper-heavy processes into one product layer the business could actually run on. I worked across the product from engineering execution into technical ownership — gathering requirements directly from stakeholders, evaluating feasibility, shaping delivery direction, and implementing the system across mobile, backend, and operational workflows.",
    challenge: "The business had multiple moving parts: customers needed to request and book commercial vehicles; staff needed to report incidents and manage daily operational tasks; vendors needed to support maintenance workflows; drivers needed document and assignment visibility; management needed dashboards for availability, expenses, utilization, and revenue; investors needed a structured shareholder flow tied to truck purchases and repayment visibility. Before this, much of the workflow depended on fragmented coordination and manual processes. That slowed execution, reduced visibility, and made it harder to scale operationally.",
    whatIOwned: "I owned the product delivery across both implementation and technical strategy: translated client requirements into scoped technical work; worked directly on the mobile and backend product flows; shaped feature feasibility and delivery sequencing; implemented operational modules used by multiple roles; supported the move from isolated workflows to one centralized product system.",
    whatIBuilt: "Key areas of delivery included: customer-side booking and request workflows; multi-role mobile experiences for operations managers, staff, drivers, vendors, and customers; shareholder/investor product flows tied to truck investment and repayment structures; dashboard visibility for revenue, expenses, utilization, and availability; electronic document-signing workflows; automated contract generation; invoice/accounting integration workflows; OCR-based verification for vehicle, driver, and customer documents.",
    outcome: "The result was a more operationally usable logistics product: booking and request workflows moved into the platform; business-critical visibility became easier through centralized dashboards; paperwork-heavy flows were digitized into structured product processes; investor, customer, and internal operations all moved closer to one system of record; day-to-day execution became more trackable and easier to manage across teams.",
    outcomeShort: "Centralized fragmented workflows into one product system.",
    proofBullets: [
      "Operational workflows centralized into one platform",
      "Replaced manual coordination with structured product flows",
      "Multi-role execution supported across customers, staff, vendors, drivers, and investors",
      "Dashboards for revenue, expenses, utilization, and availability",
      "Document workflows digitized: signing, contract generation, OCR verification",
    ],
    capabilityLine: "Mobile product delivery, backend coordination, document workflows, OCR verification, dashboarding, and accounting-linked operations",
    tags: ["React Native", "SQL", "Node.js", "Express.js", "Multi-role Platform"],
    imageUrl: "/truck.png",
    link: "https://github.com/sarmad0324/Truckwise",
    linkLabel: "View Project",
  },
  {
    slug: "triangle-wallets",
    title: "Triangle Wallets",
    subtitle: "Shipping core mobile features for a fintech wallet where reliability and trust mattered",
    homepageSummary: "Shipping core mobile fintech features where transaction clarity and reliability mattered.",
    description: "Fintech and crypto wallet application built for transaction reliability and user trust.",
    context: "Triangle Wallet publicly presents itself as a crypto/fintech wallet for buying, selling, and converting crypto, with support for 40+ cryptocurrencies and a secure mobile-first financial experience.",
    role: "Senior Engineering Contribution",
    overview: "Triangle Wallets operated in a high-trust product category where UX quality alone was not enough. In a wallet experience, users care about reliability, confidence, transaction clarity, and execution quality. My role focused on helping ship core product features in a fintech environment where consistency and trust were essential.",
    challenge: "Financial products are judged differently from normal apps. Weakness in state handling, confusing interaction flows, unstable releases, or poor reliability can quickly damage user confidence. The product needed strong execution across mobile feature delivery, wallet-related flows, and backend-connected functionality.",
    whatIOwned: "I contributed as a senior engineer across core product work: implemented and refined mobile features; supported production-oriented fintech flows; worked through backend-connected product behavior; helped improve delivery quality in a trust-sensitive environment.",
    whatIBuilt: "Core delivery areas included: wallet-related mobile experiences; transaction-oriented product flows; interface work for asset visibility and user actions; integration-heavy feature execution; production-focused iteration across a fintech UX layer.",
    outcome: "The product moved forward with stronger mobile execution in an environment where clarity, trust, and release quality mattered. My contribution supported the delivery of real product functionality, not just UI screens, in a category where user confidence is tightly tied to system behavior.",
    outcomeShort: "Stronger mobile execution in a trust-sensitive fintech environment.",
    proofBullets: [
      "Core fintech features shipped for production use",
      "Transaction-oriented flows strengthened",
      "Mobile execution improved in a trust-sensitive environment",
      "Backend-connected product behavior delivered",
    ],
    capabilityLine: "Mobile fintech product execution, API-connected flows, production feature delivery, and trust-sensitive UX implementation",
    tags: ["React Native", "Expo", "Redux", "Node.js", "MongoDB", "Blockchain"],
    imageUrl: "/triangle.png",
    link: "https://github.com/mohammadfahad112/triangle-app",
    linkLabel: "View Project",
  },
  {
    slug: "ezrecova",
    title: "EZRecova",
    subtitle: "Building a therapy and addiction-recovery platform with subscription access and AI-assisted support",
    homepageSummary: "Building a recovery-focused service platform with subscriptions, consultant access, and AI-assisted support.",
    description: "Therapy and addiction recovery subscription platform connecting users with real consultants.",
    context: "EZRecova publicly positions itself as a guided addiction-recovery platform with expert counseling, structured support, and recovery-oriented content. Public posts also reference an AI-powered support assistant tied to the platform experience.",
    role: "Technical Product Delivery Ownership",
    overview: "EZRecova was not just a content website. It needed to function as a recovery-focused digital platform where users could access support, move through structured flows, and interact with a service designed around trust, clarity, and continuity of care. I led the technical side of the product and helped shape a platform that combined business logic, user journeys, subscription-oriented access, and an AI-supported assistance layer.",
    challenge: "The platform needed to balance three different demands: present the brand and service clearly; support real user journeys around recovery and guidance; extend support with an AI assistant without making the experience feel cold or generic. That required more than standard web development. It needed product thinking around structure, user reassurance, and how support flows would actually work in practice.",
    whatIOwned: "I owned the technical product delivery across: platform implementation; structured support flows; subscription-oriented access; AI assistant integration; the broader technical setup behind the user-facing recovery experience.",
    whatIBuilt: "Core work included: the main therapy / recovery platform experience; content and service flow implementation; user pathways tied to support and recovery interaction; AI-assisted support functionality designed to extend the platform experience; technical coordination of the full product layer.",
    outcome: "The result was a more capable digital platform that went beyond simple marketing pages. The product supported service presentation, user guidance, and AI-assisted interaction in one system — making the experience feel more like an active recovery platform and less like a passive informational site.",
    outcomeShort: "Platform that supports service presentation, guidance, and AI-assisted interaction.",
    proofBullets: [
      "Subscription and support flows launched",
      "User journeys digitized around recovery and guidance",
      "AI-assisted support integrated into the platform experience",
      "Technical delivery owned across the full product layer",
    ],
    capabilityLine: "Service-platform delivery, AI-assisted support integration, subscription flow implementation, and user-journey design through technical execution",
    tags: ["WordPress", "Elementor", "Custom CSS", "PHP"],
    imageUrl: "/ezrecova.png",
    link: "https://ezrecova.com/",
    linkLabel: "View Live Product",
  },
  {
    slug: "exact-printo",
    title: "Exact Printo",
    subtitle: "Building a US packaging and printing website designed to support product discovery, quote capture, and business credibility",
    homepageSummary: "Creating a stronger digital sales and quote experience for a US packaging and printing business.",
    description: "US printing and packaging business platform with quote and commerce-support workflows.",
    context: "Exact Printo publicly markets custom packaging boxes across many categories, offers quote-based inquiry flows, highlights premium finishes and graphic support, and presents itself as a USA-based custom-box manufacturing hub.",
    role: "Business Website + Flow Execution",
    overview: "Exact Printo needed more than a generic brochure site. The business had a wide catalog, a quote-driven sales process, and a credibility problem common to packaging businesses online: if the website feels weak, the business feels weak. I worked on building a website that presented the company more professionally, made product discovery easier, and supported the commercial flow around quote requests and customer confidence.",
    challenge: "The business needed a site that could: showcase a broad range of packaging products; communicate capability and trust clearly; support quote capture; help customers navigate category-heavy offerings without confusion; make the company feel more established and commercially reliable.",
    whatIOwned: "I handled the web implementation and business-facing site delivery, with a focus on: stronger digital presentation; clearer structure across offerings; quote/conversion support; and a more professional customer-facing web experience.",
    whatIBuilt: "Core work included: business website implementation; category and product presentation layers; quote-request support flows; clearer commercial UX for browsing and inquiry; a stronger front-end experience aligned with business credibility.",
    outcome: "The result was a more professional digital presence for a US packaging company — one that better supported trust, product presentation, and customer inquiry flow. Instead of acting like a passive brochure, the site functioned more like a usable sales-support asset.",
    outcomeShort: "Professional digital presence that supports trust and inquiry flow.",
    proofBullets: [
      "Business website delivered with stronger presentation",
      "Quote-request flows implemented for commercial capture",
      "Category-heavy product structure clarified",
      "Site positioned as a sales-support asset, not a passive brochure",
    ],
    capabilityLine: "Business website delivery, quote-flow optimization, category-heavy UX, and conversion-support implementation",
    tags: ["WordPress", "Elementor", "Custom CSS", "PHP"],
    imageUrl: "/exact.png",
    link: "https://www.exactprinto.com/",
    linkLabel: "View Live Project",
  },
  {
    slug: "adodyss-growth-management",
    title: "AdOdyss Growth Management",
    description: "Growth-management platform focused on clearer offer communication and conversion flow.",
    context: "A performance team needed to translate complex service operations into cleaner decision journeys.",
    role: "Product Engineering",
    problem: "Strong services were hard to understand quickly, reducing conversion quality.",
    solution: "Rebuilt service structure, proof presentation, and conversion pathways.",
    ownership: "Led frontend implementation and product-level content architecture decisions.",
    outcome: "Created stronger inbound clarity and better high-intent conversation quality.",
    tags: ["Next.js", "React", "Conversion UX", "Service Platform"],
    imageUrl: "/adodyss.png",
    link: "https://adodyss.com/",
    linkLabel: "View Live Product",
  },
];
