import { Link, ProjectInfo } from "./types";

export const links: Link[] = [
  { nameEng: "Home", hash: "#home" },
  { nameEng: "Offers", hash: "#offers" },
  { nameEng: "Case Studies", hash: "#projects" },
  { nameEng: "About", hash: "#about" },
  { nameEng: "Contact", hash: "#contact" },
];

export const projectsData: ProjectInfo[] = [
  {
    slug: "surfbank",
    title: "SurfBank",
    subtitle: "Acting CTO Trial — a CTO-level technical and product review to shape Release 2.0, platform scalability, and AI strategy across web, backend, mobile, and a browser extension.",
    homepageSummary: "Ran a 30-day Acting CTO trial for a multi-platform knowledge-management product — auditing architecture, AI strategy, mobile direction, and operational maturity, then delivering a dependency-driven Release 2.0 roadmap that preserved existing engineering investment instead of rewriting it.",
    description: "Multi-platform knowledge management and content organization platform (Next.js web, .NET/MySQL backend, native Android and iOS apps, and a browser extension).",
    featuredBadge: "Featured · Paid Technical Audit",
    context: "SurfBank is a multi-platform knowledge management and content organization platform spanning a Next.js web app, a .NET / MySQL backend, native Android (Kotlin) and iOS (Swift) apps, and a browser extension.",
    role: "Acting CTO Trial",
    overview: "SurfBank is a multi-platform knowledge management and content organization platform — a Next.js web app, a .NET / MySQL backend, native Android (Kotlin) and iOS (Swift) apps, and a browser extension. The founders engaged me for a CTO-level technical and product review focused on Release 2.0 planning, platform scalability, AI strategy, mobile architecture, search, and operational maturity. The engagement was structured as a 30-day CTO trial.",
    challenge: "SurfBank had already invested heavily across multiple platforms, so the question was never whether the product could be built — it was what should happen next. Could the current architecture support the next stage of growth? Should the stack be retained or replaced? How should AI and search be introduced? Should mobile stay native? What roadmap should Release 2.0 follow? The founders needed an independent CTO perspective before committing to major product and engineering decisions.",
    whatIOwned: "I evaluated SurfBank as a complete product ecosystem rather than reviewing repositories in isolation — across the product layer (user journeys, workspaces, content capture, search and discovery), the application layer (web, Android, iOS, browser extension), the platform layer (backend, APIs, authentication, data ownership, infrastructure), and the strategic layer (AI direction, team structure, scaling, release planning, operational maturity). The work spanned a product audit, architecture review, AI strategy, scalability assessment, and a prioritized roadmap. The objective was not to find bugs — it was to determine how SurfBank should evolve technically while protecting existing engineering investment.",
    deliveryHeading: "Key Findings & Recommendations",
    whatIBuilt: "No rewrite. Retain the .NET backend, MySQL, and Next.js web platform and pursue controlled modernization instead of premature microservices or stack replacement. Make search the core AI strategy — start with content, people, metadata, and permission-safe retrieval before recommendation engines or chat, because strong search creates immediate value and the measurable usage signals that future AI depends on. Consolidate mobile by stabilizing the native Android/iOS apps and aligning platform contracts now, then migrating gradually toward React Native once those contracts are stable — not a full rewrite. Move content capture into a backend-owned processing pipeline (minimal save → queue → metadata extraction → language detection → indexing → search availability). Treat language expansion as architecture, not translation, by separating interface language, user region, original content language, and the translation layer. Add a formal offline strategy with a hybrid local + cloud model, and raise operational maturity with error tracking, monitoring, release controls, recovery validation, and deployment governance.",
    outcome: "The founders left with a clear, independent CTO assessment and a dependency-driven Release 2.0 roadmap — structured across seven workstreams: platform stabilization, first-value experience, content capture & metadata, search & AI, mobile continuity, workspaces & community, and release readiness. The key conclusion: SurfBank's next challenge wasn't building more features. It was transforming an existing multi-platform product into a scalable, searchable, operationally mature platform ready for AI-driven capabilities — without unnecessary rewrites.",
    outcomeShort: "A 30-day Acting CTO trial: independent architecture, AI, and mobile assessment plus a dependency-driven Release 2.0 roadmap — modernize, don't rewrite.",
    proofBullets: [
      "Multi-platform technical assessment across web, backend, mobile, and browser extension",
      "Search-first AI strategy with a clear capture → index → retrieve → recommend path",
      "Mobile modernization plan: stabilize native now, migrate to React Native later",
      "Backend-owned content capture and metadata processing pipeline",
      "Scalable multilingual architecture separating interface, region, and content language",
      "Dependency-driven Release 2.0 framework across seven workstreams",
      "Operational maturity roadmap: monitoring, release controls, deployment governance",
    ],
    capabilityLine: "CTO-level product and architecture review, AI and search strategy, mobile modernization, scalability assessment, and release planning — without unnecessary rewrites.",
    tags: ["Acting CTO", "Technical Audit", "Architecture Review", "AI Strategy", ".NET", "Next.js", "React Native"],
    imageUrl: "/surfbankweb.png",
    gallery: [
      { src: "/surfbankweb.png", alt: "SurfBank web platform", orientation: "landscape" },
      { src: "/surfbankapp.jpeg", alt: "SurfBank mobile app", orientation: "portrait" },
    ],
    link: "",
    ctaLabel: "Want the same clarity for your product? Book an Audit.",
    ctaHref: "https://calendly.com/sarmad-sarmadirfan/30min",
  },
  {
    slug: "truckwise",
    title: "TruckWise",
    subtitle: "Digitizing commercial vehicle rental, investor workflows, and daily fleet operations in one product system",
    homepageSummary: "Digitized a paper-heavy logistics and commercial vehicle rental operation into one centralized product system across bookings, fleet workflows, investor/shareholder flows, OCR verification, contract signing, and accounting-linked invoicing.",
    description: "Logistics and commercial vehicle rental platform with centralized multi-role operations.",
    context: "TruckWise operates in logistics and transport, with a strong emphasis on performance, data, and operational visibility. Its public-facing brand also highlights tech-enabled execution and disciplined logistics delivery.",
    role: "Execution + Strategy Ownership",
    overview: "TruckWise is a logistics and commercial vehicle rental platform with investor/shareholder workflows and multi-role operations. The business needed more than a booking interface — it had complexity across bookings, incidents, maintenance, dashboards, OCR verification, document signing, invoicing/accounting, and more. I worked from engineering execution into requirement analysis, feasibility, strategy, and implementation ownership.",
    challenge: "Product was blocked. Fragmented manual workflows across 5+ role types — customers, staff, vendors, drivers, management, investors. No single system of record. Coordination was manual. Execution slowed. Visibility was low.",
    whatIOwned: "I moved from engineering execution into requirement analysis, feasibility, strategy, and implementation ownership. Translated stakeholder needs into scoped work. Shaped feature sequencing. Implemented the full system across mobile, backend, and operational workflows.",
    whatIBuilt: "Key areas of delivery included: customer-side booking and request workflows; multi-role mobile experiences for operations managers, staff, drivers, vendors, and customers; shareholder/investor product flows tied to truck investment and repayment structures; dashboard visibility for revenue, expenses, utilization, and availability; electronic document-signing workflows; automated contract generation; invoice/accounting integration workflows; OCR-based verification for vehicle, driver, and customer documents.",
    outcome: "Transformed fragmented manual workflows into one centralized product system. Bookings, fleet workflows, investor flows, OCR verification, contract signing, and accounting-linked invoicing now run through one platform. Execution moved from blocked to ship-ready.",
    outcomeShort: "5+ role types unified into one product system over 2 years of continuous delivery. Execution moved from blocked to ship-ready.",
    proofBullets: [
      "Operational workflows centralized into one platform",
      "Replaced manual coordination with structured product flows",
      "Multi-role execution supported across customers, staff, vendors, drivers, and investors",
      "Dashboards for revenue, expenses, utilization, and availability",
      "Document workflows digitized: signing, contract generation, OCR verification",
    ],
    capabilityLine: "Mobile product delivery, backend coordination, document workflows, OCR verification, dashboarding, and accounting-linked operations",
    tags: ["React Native", "SQL", "Node.js", "Express.js", "Multi-role Platform"],
    imageUrl: "/truck.png",
    link: "https://github.com/sarmad0324/Truckwise",
    linkLabel: "View Project",
  },
  {
    slug: "triangle-wallets",
    title: "Triangle Wallets",
    subtitle: "Shipping core mobile features for a fintech wallet where reliability and trust mattered",
    homepageSummary: "Shipped core mobile fintech features in a high-trust wallet environment where transaction clarity, product reliability, and clean execution directly affected user confidence.",
    description: "Fintech and crypto wallet application built for transaction reliability and user trust.",
    context: "Triangle Wallet publicly presents itself as a crypto/fintech wallet for buying, selling, and converting crypto, with support for 40+ cryptocurrencies and a secure mobile-first financial experience.",
    role: "Senior Engineering Contribution",
    overview: "Triangle Wallets operated in a high-trust product category where UX quality alone was not enough. In a wallet experience, users care about reliability, confidence, transaction clarity, and execution quality. My role focused on helping ship core product features in a fintech environment where consistency and trust were essential.",
    challenge: "Delivery was messy. Financial products are judged differently — weakness in state handling, confusing flows, or unstable releases can quickly damage user confidence. The product needed strong execution across mobile, wallet flows, and backend-connected functionality. Without it, trust erodes fast.",
    whatIOwned: "Senior engineering contribution across mobile and backend-connected product execution. Implemented core fintech flows. Supported production-oriented wallet features. Delivered in an environment where transaction clarity and reliability directly affected user confidence.",
    whatIBuilt: "Core delivery areas included: wallet-related mobile experiences; transaction-oriented product flows; interface work for asset visibility and user actions; integration-heavy feature execution; production-focused iteration across a fintech UX layer.",
    outcome: "Mobile execution strengthened. Core fintech flows shipped for production. Transaction clarity and release quality improved. Real product functionality, not just UI — in a category where user confidence is tightly tied to system behavior.",
    outcomeShort: "Core wallet features shipped. Trust-sensitive environment stabilized.",
    proofBullets: [
      "Core fintech features shipped for production use",
      "Transaction-oriented flows strengthened",
      "Mobile execution improved in a trust-sensitive environment",
      "Backend-connected product behavior delivered",
    ],
    capabilityLine: "Mobile fintech product execution, API-connected flows, production feature delivery, and trust-sensitive UX implementation",
    tags: ["React Native", "Expo", "Redux", "Node.js", "MongoDB", "Blockchain"],
    imageUrl: "/triangle.png",
    link: "https://github.com/mohammadfahad112/triangle-app",
    linkLabel: "View Project",
  },
  {
    slug: "ezrecova",
    title: "EZRecova",
    subtitle: "Building a therapy and addiction-recovery platform with subscription access and AI-assisted support",
    homepageSummary: "Built a recovery-focused digital platform combining subscription access, consultant interaction, and AI-assisted support into one structured service experience.",
    description: "Therapy and addiction recovery subscription platform connecting users with real consultants.",
    context: "EZRecova publicly positions itself as a guided addiction-recovery platform with expert counseling, structured support, and recovery-oriented content. Public posts also reference an AI-powered support assistant tied to the platform experience.",
    role: "Technical Product Delivery Ownership",
    overview: "EZRecova was not just a content website. It needed to function as a recovery-focused digital platform where users could access support, move through structured flows, and interact with a service designed around trust, clarity, and continuity of care. I led the technical side of the product and helped shape a platform that combined business logic, user journeys, subscription-oriented access, and an AI-supported assistance layer.",
    challenge: "Frontend, backend, and integrations were disconnected. The platform needed to balance three demands: present the brand clearly; support real user journeys around recovery; extend support with AI without feeling cold. Standard web development wasn't enough. Product thinking, structure, and support flows were missing.",
    whatIOwned: "Technical product delivery ownership. Platform implementation, subscription flows, consultant interaction, AI-assisted support — all unified into one structured service experience.",
    whatIBuilt: "Core work included: the main therapy / recovery platform experience; content and service flow implementation; user pathways tied to support and recovery interaction; AI-assisted support functionality designed to extend the platform experience; technical coordination of the full product layer.",
    outcome: "One system replaced disconnected pieces. Service presentation, user guidance, and AI-assisted interaction unified. The experience moved from passive informational site to active recovery platform.",
    outcomeShort: "Subscription flows, user journeys, and AI support unified into one platform.",
    proofBullets: [
      "Subscription and support flows launched",
      "User journeys digitized around recovery and guidance",
      "AI-assisted support integrated into the platform experience",
      "Technical delivery owned across the full product layer",
    ],
    capabilityLine: "Service-platform delivery, AI-assisted support integration, subscription flow implementation, and user-journey design through technical execution",
    tags: ["WordPress", "Elementor", "Custom CSS", "PHP"],
    imageUrl: "/ezrecova.png",
    link: "https://ezrecova.com/",
    linkLabel: "View Live Product",
  },
  {
    slug: "exact-printo",
    title: "Exact Printo",
    subtitle: "Building a US packaging and printing website designed to support product discovery, quote capture, and business credibility",
    homepageSummary: "Created a stronger quote-driven digital presence for a US packaging and printing business, improving product presentation, inquiry flow, and overall commercial credibility.",
    description: "US printing and packaging business platform with quote and commerce-support workflows.",
    context: "Exact Printo publicly markets custom packaging boxes across many categories, offers quote-based inquiry flows, highlights premium finishes and graphic support, and presents itself as a USA-based custom-box manufacturing hub.",
    role: "Business Website + Flow Execution",
    overview: "Exact Printo needed more than a generic brochure site. The business had a wide catalog, a quote-driven sales process, and a credibility problem common to packaging businesses online: if the website feels weak, the business feels weak. I worked on building a website that presented the company more professionally, made product discovery easier, and supported the commercial flow around quote requests and customer confidence.",
    challenge: "Product was blocked by poor digital execution. The site couldn't showcase a broad catalog, communicate trust, or capture quotes effectively. Category-heavy offerings confused customers. The company felt weak online — credibility was at stake.",
    whatIOwned: "Web implementation and business-facing delivery. Stronger digital presentation. Quote/inquiry flow. A site that supports trust and sales — not a passive brochure.",
    whatIBuilt: "Core work included: business website implementation; category and product presentation layers; quote-request support flows; clearer commercial UX for browsing and inquiry; a stronger front-end experience aligned with business credibility.",
    outcome: "Professional digital presence delivered. Trust, product presentation, and quote flow strengthened. The site moved from passive brochure to usable sales-support asset.",
    outcomeShort: "Quote flow fixed. Digital credibility established.",
    proofBullets: [
      "Business website delivered with stronger presentation",
      "Quote-request flows implemented for commercial capture",
      "Category-heavy product structure clarified",
      "Site positioned as a sales-support asset, not a passive brochure",
    ],
    capabilityLine: "Business website delivery, quote-flow optimization, category-heavy UX, and conversion-support implementation",
    tags: ["WordPress", "Elementor", "Custom CSS", "PHP"],
    imageUrl: "/exact.png",
    link: "https://www.exactprinto.com/",
    linkLabel: "View Live Project",
  },
  {
    slug: "adodyss-growth-management",
    title: "AdOdyss Growth Management",
    description: "Growth-management platform focused on clearer offer communication and conversion flow.",
    context: "A performance team needed to translate complex service operations into cleaner decision journeys.",
    role: "Product Engineering",
    overview: "AdOdyss is a growth-management platform. The team had strong services but needed product execution to turn complexity into clarity.",
    problem: "Strong services were hard to understand quickly. Conversion quality suffered. The frontend and offer structure lacked technical ownership — nothing connected clearly.",
    ownership: "I owned frontend implementation and product-level content architecture. Rebuilt service structure, proof presentation, and conversion pathways.",
    outcome: "Stronger inbound clarity. Better high-intent conversation quality. Conversion pathways that actually convert.",
    tags: ["Next.js", "React", "Conversion UX", "Service Platform"],
    imageUrl: "/adodyss.png",
    link: "https://adodyss.com/",
    linkLabel: "View Live Product",
  },
];
