import { Link, ProjectInfo } from "./types";

export const links: Link[] = [
  { nameEng: "Home", hash: "#home" },
  { nameEng: "Offers", hash: "#offers" },
  { nameEng: "Case Studies", hash: "#projects" },
  { nameEng: "About", hash: "#about" },
  { nameEng: "Contact", hash: "#contact" },
];

export const projectsData: ProjectInfo[] = [
  {
    slug: "truckwise",
    title: "TruckWise",
    subtitle: "Digitizing commercial vehicle rental, investor workflows, and daily fleet operations in one product system",
    homepageSummary: "Digitized a paper-heavy logistics and commercial vehicle rental operation into one centralized product system across bookings, fleet workflows, investor/shareholder flows, OCR verification, contract signing, and accounting-linked invoicing.",
    description: "Logistics and commercial vehicle rental platform with centralized multi-role operations.",
    context: "TruckWise operates in logistics and transport, with a strong emphasis on performance, data, and operational visibility. Its public-facing brand also highlights tech-enabled execution and disciplined logistics delivery.",
    role: "Execution + Strategy Ownership",
    overview: "TruckWise is a logistics and commercial vehicle rental platform with investor/shareholder workflows and multi-role operations. The business needed more than a booking interface — it had complexity across bookings, incidents, maintenance, dashboards, OCR verification, document signing, invoicing/accounting, and more. I worked from engineering execution into requirement analysis, feasibility, strategy, and implementation ownership.",
    challenge: "Product was blocked. Fragmented manual workflows across 5+ role types — customers, staff, vendors, drivers, management, investors. No single system of record. Coordination was manual. Execution slowed. Visibility was low.",
    whatIOwned: "I moved from engineering execution into requirement analysis, feasibility, strategy, and implementation ownership. Translated stakeholder needs into scoped work. Shaped feature sequencing. Implemented the full system across mobile, backend, and operational workflows.",
    whatIBuilt: "Key areas of delivery included: customer-side booking and request workflows; multi-role mobile experiences for operations managers, staff, drivers, vendors, and customers; shareholder/investor product flows tied to truck investment and repayment structures; dashboard visibility for revenue, expenses, utilization, and availability; electronic document-signing workflows; automated contract generation; invoice/accounting integration workflows; OCR-based verification for vehicle, driver, and customer documents.",
    outcome: "Transformed fragmented manual workflows into one centralized product system. Bookings, fleet workflows, investor flows, OCR verification, contract signing, and accounting-linked invoicing now run through one platform. Execution moved from blocked to ship-ready.",
    outcomeShort: "5+ role types unified into one product system. Execution moved from blocked to ship-ready.",
    proofBullets: [
      "Operational workflows centralized into one platform",
      "Replaced manual coordination with structured product flows",
      "Multi-role execution supported across customers, staff, vendors, drivers, and investors",
      "Dashboards for revenue, expenses, utilization, and availability",
      "Document workflows digitized: signing, contract generation, OCR verification",
    ],
    capabilityLine: "Mobile product delivery, backend coordination, document workflows, OCR verification, dashboarding, and accounting-linked operations",
    tags: ["React Native", "SQL", "Node.js", "Express.js", "Multi-role Platform"],
    imageUrl: "/truck.png",
    link: "https://github.com/sarmad0324/Truckwise",
    linkLabel: "View Project",
  },
  {
    slug: "triangle-wallets",
    title: "Triangle Wallets",
    subtitle: "Shipping core mobile features for a fintech wallet where reliability and trust mattered",
    homepageSummary: "Shipped core mobile fintech features in a high-trust wallet environment where transaction clarity, product reliability, and clean execution directly affected user confidence.",
    description: "Fintech and crypto wallet application built for transaction reliability and user trust.",
    context: "Triangle Wallet publicly presents itself as a crypto/fintech wallet for buying, selling, and converting crypto, with support for 40+ cryptocurrencies and a secure mobile-first financial experience.",
    role: "Senior Engineering Contribution",
    overview: "Triangle Wallets operated in a high-trust product category where UX quality alone was not enough. In a wallet experience, users care about reliability, confidence, transaction clarity, and execution quality. My role focused on helping ship core product features in a fintech environment where consistency and trust were essential.",
    challenge: "Delivery was messy. Financial products are judged differently — weakness in state handling, confusing flows, or unstable releases can quickly damage user confidence. The product needed strong execution across mobile, wallet flows, and backend-connected functionality. Without it, trust erodes fast.",
    whatIOwned: "Senior engineering contribution across mobile and backend-connected product execution. Implemented core fintech flows. Supported production-oriented wallet features. Delivered in an environment where transaction clarity and reliability directly affected user confidence.",
    whatIBuilt: "Core delivery areas included: wallet-related mobile experiences; transaction-oriented product flows; interface work for asset visibility and user actions; integration-heavy feature execution; production-focused iteration across a fintech UX layer.",
    outcome: "Mobile execution strengthened. Core fintech flows shipped for production. Transaction clarity and release quality improved. Real product functionality, not just UI — in a category where user confidence is tightly tied to system behavior.",
    outcomeShort: "Core wallet features shipped. Trust-sensitive environment stabilized.",
    proofBullets: [
      "Core fintech features shipped for production use",
      "Transaction-oriented flows strengthened",
      "Mobile execution improved in a trust-sensitive environment",
      "Backend-connected product behavior delivered",
    ],
    capabilityLine: "Mobile fintech product execution, API-connected flows, production feature delivery, and trust-sensitive UX implementation",
    tags: ["React Native", "Expo", "Redux", "Node.js", "MongoDB", "Blockchain"],
    imageUrl: "/triangle.png",
    link: "https://github.com/mohammadfahad112/triangle-app",
    linkLabel: "View Project",
  },
  {
    slug: "ezrecova",
    title: "EZRecova",
    subtitle: "Building a therapy and addiction-recovery platform with subscription access and AI-assisted support",
    homepageSummary: "Built a recovery-focused digital platform combining subscription access, consultant interaction, and AI-assisted support into one structured service experience.",
    description: "Therapy and addiction recovery subscription platform connecting users with real consultants.",
    context: "EZRecova publicly positions itself as a guided addiction-recovery platform with expert counseling, structured support, and recovery-oriented content. Public posts also reference an AI-powered support assistant tied to the platform experience.",
    role: "Technical Product Delivery Ownership",
    overview: "EZRecova was not just a content website. It needed to function as a recovery-focused digital platform where users could access support, move through structured flows, and interact with a service designed around trust, clarity, and continuity of care. I led the technical side of the product and helped shape a platform that combined business logic, user journeys, subscription-oriented access, and an AI-supported assistance layer.",
    challenge: "Frontend, backend, and integrations were disconnected. The platform needed to balance three demands: present the brand clearly; support real user journeys around recovery; extend support with AI without feeling cold. Standard web development wasn't enough. Product thinking, structure, and support flows were missing.",
    whatIOwned: "Technical product delivery ownership. Platform implementation, subscription flows, consultant interaction, AI-assisted support — all unified into one structured service experience.",
    whatIBuilt: "Core work included: the main therapy / recovery platform experience; content and service flow implementation; user pathways tied to support and recovery interaction; AI-assisted support functionality designed to extend the platform experience; technical coordination of the full product layer.",
    outcome: "One system replaced disconnected pieces. Service presentation, user guidance, and AI-assisted interaction unified. The experience moved from passive informational site to active recovery platform.",
    outcomeShort: "Subscription flows, user journeys, and AI support unified into one platform.",
    proofBullets: [
      "Subscription and support flows launched",
      "User journeys digitized around recovery and guidance",
      "AI-assisted support integrated into the platform experience",
      "Technical delivery owned across the full product layer",
    ],
    capabilityLine: "Service-platform delivery, AI-assisted support integration, subscription flow implementation, and user-journey design through technical execution",
    tags: ["WordPress", "Elementor", "Custom CSS", "PHP"],
    imageUrl: "/ezrecova.png",
    link: "https://ezrecova.com/",
    linkLabel: "View Live Product",
  },
  {
    slug: "exact-printo",
    title: "Exact Printo",
    subtitle: "Building a US packaging and printing website designed to support product discovery, quote capture, and business credibility",
    homepageSummary: "Created a stronger quote-driven digital presence for a US packaging and printing business, improving product presentation, inquiry flow, and overall commercial credibility.",
    description: "US printing and packaging business platform with quote and commerce-support workflows.",
    context: "Exact Printo publicly markets custom packaging boxes across many categories, offers quote-based inquiry flows, highlights premium finishes and graphic support, and presents itself as a USA-based custom-box manufacturing hub.",
    role: "Business Website + Flow Execution",
    overview: "Exact Printo needed more than a generic brochure site. The business had a wide catalog, a quote-driven sales process, and a credibility problem common to packaging businesses online: if the website feels weak, the business feels weak. I worked on building a website that presented the company more professionally, made product discovery easier, and supported the commercial flow around quote requests and customer confidence.",
    challenge: "Product was blocked by poor digital execution. The site couldn't showcase a broad catalog, communicate trust, or capture quotes effectively. Category-heavy offerings confused customers. The company felt weak online — credibility was at stake.",
    whatIOwned: "Web implementation and business-facing delivery. Stronger digital presentation. Quote/inquiry flow. A site that supports trust and sales — not a passive brochure.",
    whatIBuilt: "Core work included: business website implementation; category and product presentation layers; quote-request support flows; clearer commercial UX for browsing and inquiry; a stronger front-end experience aligned with business credibility.",
    outcome: "Professional digital presence delivered. Trust, product presentation, and quote flow strengthened. The site moved from passive brochure to usable sales-support asset.",
    outcomeShort: "Quote flow fixed. Digital credibility established.",
    proofBullets: [
      "Business website delivered with stronger presentation",
      "Quote-request flows implemented for commercial capture",
      "Category-heavy product structure clarified",
      "Site positioned as a sales-support asset, not a passive brochure",
    ],
    capabilityLine: "Business website delivery, quote-flow optimization, category-heavy UX, and conversion-support implementation",
    tags: ["WordPress", "Elementor", "Custom CSS", "PHP"],
    imageUrl: "/exact.png",
    link: "https://www.exactprinto.com/",
    linkLabel: "View Live Project",
  },
  {
    slug: "adodyss-growth-management",
    title: "AdOdyss Growth Management",
    description: "Growth-management platform focused on clearer offer communication and conversion flow.",
    context: "A performance team needed to translate complex service operations into cleaner decision journeys.",
    role: "Product Engineering",
    overview: "AdOdyss is a growth-management platform. The team had strong services but needed product execution to turn complexity into clarity.",
    problem: "Strong services were hard to understand quickly. Conversion quality suffered. The frontend and offer structure lacked technical ownership — nothing connected clearly.",
    ownership: "I owned frontend implementation and product-level content architecture. Rebuilt service structure, proof presentation, and conversion pathways.",
    outcome: "Stronger inbound clarity. Better high-intent conversation quality. Conversion pathways that actually convert.",
    tags: ["Next.js", "React", "Conversion UX", "Service Platform"],
    imageUrl: "/adodyss.png",
    link: "https://adodyss.com/",
    linkLabel: "View Live Product",
  },
];
